# Generated by Django 6.0.4 on 2026-04-22 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assetcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('GITHUB', 'GitHub'), ('GOOGLE_WORKSPACE', 'Google Workspace'), ('AZURE_AD', 'Azure AD'), ('SLACK', 'Slack'), ('JIRA', 'Jira'), ('FIGMA', 'Figma'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('login_email', models.CharField(max_length=255)),
                ('account_url', models.URLField(blank=True, null=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('subscription_plan', models.CharField(blank=True, max_length=100)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaultCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('encrypted_password', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('GITHUB', 'GitHub'), ('GOOGLE', 'Google'), ('AWS', 'AWS'), ('AZURE', 'Azure'), ('DATABASE', 'Database'), ('SERVER', 'Server'), ('SOCIAL', 'Social'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('workspace_tag', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
