# Generated by Django 6.0.4 on 2026-04-24 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_office_checklisttemplate_checklisttemplateitem_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('HARDWARE_SUPPLIER', 'Hardware Supplier'), ('SOFTWARE_VENDOR', 'Software Vendor'), ('SERVICE_PROVIDER', 'Service Provider'), ('TELECOM', 'Telecom'), ('CLOUD', 'Cloud Provider'), ('MAINTENANCE', 'Maintenance'), ('CONSULTANT', 'Consultant'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='softwarelicense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_licenses', to='core.vendor'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.vendor'),
        ),
        migrations.AlterField(
            model_name='recurringbill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bills', to='core.vendor'),
        ),
        migrations.CreateModel(
            name='VendorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('contract_type', models.CharField(choices=[('AMC', 'Annual Maintenance Contract'), ('SLA', 'Service Level Agreement'), ('PURCHASE', 'Purchase Agreement'), ('SERVICE', 'Service Agreement'), ('LICENSE', 'Software License'), ('NDA', 'Non-Disclosure Agreement'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('RENEWED', 'Renewed')], default='DRAFT', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('terms_summary', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_notes', to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CARD', 'Credit/Debit Card'), ('CASH', 'Cash')], default='BANK_TRANSFER', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.vendorcontract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.vendor')),
            ],
        ),
    ]
