# Generated by Django 6.0.4 on 2026-04-24 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_purchaserequest_prdocument_prapprovallog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('network_address', models.CharField(max_length=50)),
                ('subnet_mask', models.CharField(default='255.255.255.0', max_length=50)),
                ('cidr_prefix', models.PositiveIntegerField(default=24)),
                ('gateway', models.CharField(blank=True, max_length=50, null=True)),
                ('vlan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('SERVER_ROOM', 'Server Room'), ('RACK', 'Rack'), ('CABINET', 'Cabinet'), ('FLOOR', 'Floor'), ('BUILDING', 'Building'), ('CLOUD', 'Cloud')], default='SERVER_ROOM', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_locations', to='core.office')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('device_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('device_type', models.CharField(choices=[('SERVER', 'Server'), ('SWITCH', 'Switch'), ('ROUTER', 'Router'), ('FIREWALL', 'Firewall'), ('ACCESS_POINT', 'Access Point'), ('NAS', 'NAS'), ('UPS', 'UPS'), ('PATCH_PANEL', 'Patch Panel'), ('CABLE_MODEM', 'Cable Modem'), ('VM', 'Virtual Machine'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('rack_unit_start', models.PositiveIntegerField(blank=True, null=True)),
                ('rack_unit_size', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance'), ('DECOMMISSIONED', 'Decommissioned')], default='OFFLINE', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('subnet_mask', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway', models.CharField(blank=True, max_length=50, null=True)),
                ('dns_primary', models.CharField(blank=True, max_length=50, null=True)),
                ('dns_secondary', models.CharField(blank=True, max_length=50, null=True)),
                ('vlan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('os_name', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_info', models.CharField(blank=True, max_length=255, null=True)),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_info', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('last_seen_online', models.DateTimeField(blank=True, null=True)),
                ('uptime_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linked_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_devices', to='core.asset')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_devices', to='core.vendor')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='core.networklocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_notes', to='core.networkdevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevicePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.PositiveIntegerField()),
                ('port_name', models.CharField(blank=True, max_length=50, null=True)),
                ('port_type', models.CharField(choices=[('ETHERNET', 'Ethernet'), ('FIBER', 'Fiber'), ('USB', 'USB'), ('CONSOLE', 'Console'), ('MGMT', 'Management')], default='ETHERNET', max_length=20)),
                ('connected_to_port', models.PositiveIntegerField(blank=True, null=True)),
                ('speed_mbps', models.PositiveIntegerField(blank=True, null=True)),
                ('is_uplink', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('connected_to_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_ports', to='core.networkdevice')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='core.networkdevice')),
            ],
            options={
                'ordering': ['port_number'],
                'unique_together': {('device', 'port_number')},
            },
        ),
    ]
