# Generated by Django 6.0.4 on 2026-05-04 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_department_code_department_head_department_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorMapObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('SEAT', 'Seat'), ('TABLE', 'Table'), ('ROOM', 'Room'), ('TEXT', 'Text')], max_length=10)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=40)),
                ('height', models.FloatField(default=40)),
                ('rotation', models.FloatField(default=0)),
                ('z_index', models.IntegerField(default=0)),
                ('locked', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_objects', to='core.floor')),
                ('seat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_object', to='core.seat')),
            ],
            options={
                'ordering': ['z_index', 'id'],
            },
        ),
    ]
