# Generated by Django 6.0.4 on 2026-05-14 05:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_floormapobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REPAIR', 'Repair'), ('UPGRADE', 'Upgrade'), ('SERVICE', 'Routine Service'), ('REPLACEMENT', 'Part Replacement'), ('OTHER', 'Other')], default='REPAIR', max_length=20)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('performed_on', models.DateField(default=django.utils.timezone.now)),
                ('downtime_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-performed_on', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='assethistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='assetnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(choices=[('STRAIGHT_LINE', 'Straight-line'), ('NONE', 'No depreciation')], default='STRAIGHT_LINE', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Residual book value at end of useful life.', max_digits=14),
        ),
        migrations.AddField(
            model_name='asset',
            name='useful_life_months',
            field=models.PositiveIntegerField(blank=True, help_text='Useful life in months for depreciation. Typical: hardware 36, peripherals 24, server 60.', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('LICENSE', 'License'), ('PERIPHERAL', 'Peripheral'), ('OTHER', 'Other')], db_index=True, default='HARDWARE', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('UNDER_REPAIR', 'Under Repair'), ('RETIRED', 'Retired'), ('LOST', 'Lost')], db_index=True, default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'asset_type'], name='core_asset_status_d4be83_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['warranty_expiry'], name='core_asset_warrant_f58a77_idx'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='core.asset'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_events', to='core.vendor'),
        ),
    ]
