# Generated by Django 6.0.4 on 2026-05-14 05:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_assetmaintenance_alter_asset_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=40)),
                ('address', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Asset categories'},
        ),
        migrations.AddField(
            model_name='asset',
            name='specs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='bulk_allowed',
            field=models.BooleanField(default=False, help_text='If True, the asset form lets users create N rows in one submit.'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='code',
            field=models.SlugField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='icon',
            field=models.CharField(blank=True, default='', help_text="Optional lucide-react icon name (e.g. 'Laptop', 'Keyboard').", max_length=40),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='is_serialized',
            field=models.BooleanField(default=True, help_text='If True, each physical unit gets its own Asset row with a unique serial.'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='spec_schema',
            field=models.JSONField(blank=True, default=list, help_text='List of spec field definitions for assets in this category.'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.location'),
        ),
    ]
