# Generated by Django 6.0.4 on 2026-05-14 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_location_alter_assetcategory_options_asset_specs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='quantity_total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AssetUnitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_assignments', to='core.asset')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_units_assigned', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_unit_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-assigned_date'],
            },
        ),
    ]
