# Generated by Django 6.0.4 on 2026-05-14 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_asset_quantity_total_assetunitassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_expiry', models.DateField(blank=True, null=True)),
                ('new_expiry', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('seats_added', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='core.softwarelicense')),
                ('renewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_renewals_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-renewed_at'],
            },
        ),
    ]
