# Generated by Django 6.0.4 on 2026-05-14 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_licenserenewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarelicense',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='performed_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
