# Generated by Django 6.0.4 on 2026-05-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_softwarelicense_auto_renew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='affected_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
