# Generated by Django 6.0.4 on 2026-05-19 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_asset_unit_price_assetmaintenance_affected_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultcredential',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='last_revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='last_revealed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revealed_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='reveal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='rotation_due_at',
            field=models.DateField(blank=True, help_text='Optional reminder to rotate this credential', null=True),
        ),
        migrations.CreateModel(
            name='VaultMasterPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('set_at', models.DateTimeField(auto_now=True)),
                ('rotation_count', models.PositiveIntegerField(default=0)),
                ('session_ttl_minutes', models.PositiveIntegerField(default=30)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_vault_passwords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaultUnlockSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('revoked', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
