# Generated by Django 6.0.4 on 2026-05-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_vaultcredential_is_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountworkspace',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountworkspace',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual'), ('CUSTOM', 'Custom / One-off')], default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='accountworkspace',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='accountworkspace',
            name='last_renewed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountworkspace',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountworkspace',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='accountworkspace',
            name='support_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='encrypted_custom_fields',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='encrypted_recovery_codes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='encrypted_totp_secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vaultcredential',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='core.accountworkspace'),
        ),
        migrations.AlterField(
            model_name='accountworkspace',
            name='platform',
            field=models.CharField(choices=[('GITHUB', 'GitHub'), ('GOOGLE_WORKSPACE', 'Google Workspace'), ('AZURE_AD', 'Azure AD'), ('SLACK', 'Slack'), ('JIRA', 'Jira'), ('FIGMA', 'Figma'), ('AWS', 'AWS'), ('NOTION', 'Notion'), ('LINEAR', 'Linear'), ('CLOUDFLARE', 'Cloudflare'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='vaultcredential',
            name='category',
            field=models.CharField(choices=[('GITHUB', 'GitHub'), ('GOOGLE', 'Google'), ('AWS', 'AWS'), ('AZURE', 'Azure'), ('DATABASE', 'Database'), ('SERVER', 'Server'), ('SOCIAL', 'Social'), ('EMAIL', 'Email'), ('SSH', 'SSH Key'), ('API', 'API Key'), ('WIFI', 'Wi-Fi'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
