# Generated by Django 6.0.4 on 2026-05-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_accountworkspace_auto_renew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floormapobject',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='floormapobject',
            name='elevation',
            field=models.FloatField(default=0, help_text='Height off the floor for the 3D view'),
        ),
        migrations.AlterField(
            model_name='floormapobject',
            name='object_type',
            field=models.CharField(choices=[('WORKSTATION', 'Workstation'), ('CABIN', 'Cabin'), ('HOT_DESK', 'Hot Desk'), ('MEETING_ROOM', 'Meeting Room'), ('DESK', 'Desk'), ('CHAIR', 'Chair'), ('TABLE', 'Table'), ('WALL', 'Wall'), ('DOOR', 'Door'), ('PLANT', 'Plant'), ('ROOM', 'Room'), ('TEXT', 'Text'), ('SEAT', 'Seat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seat',
            name='grid_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seat',
            name='grid_y',
            field=models.IntegerField(default=0),
        ),
    ]
