# Generated by Django 6.0.4 on 2026-05-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_floormapobject_color_floormapobject_elevation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('WORKSTATION', 'Workstation'), ('CABIN', 'Cabin'), ('HOT_DESK', 'Hot Desk'), ('MEETING_ROOM', 'Meeting Room'), ('DESK', 'Desk'), ('ROOM', 'Room'), ('STORAGE', 'Storage')], default='WORKSTATION', max_length=20),
        ),
    ]
