# Generated by Django 6.0.4 on 2026-05-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_seat_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floormapobject',
            name='object_type',
            field=models.CharField(choices=[('WORKSTATION', 'Workstation'), ('CABIN', 'Cabin'), ('HOT_DESK', 'Hot Desk'), ('MEETING_ROOM', 'Meeting Room'), ('DESK', 'Desk'), ('CHAIR', 'Chair'), ('TABLE', 'Table'), ('WALL', 'Wall'), ('DOOR', 'Door'), ('PLANT', 'Plant'), ('ROOM', 'Room'), ('TEXT', 'Text'), ('CAFE', 'Cafe / Pantry'), ('RECEPTION', 'Reception'), ('PRINTER', 'Printer'), ('WHITEBOARD', 'Whiteboard'), ('SEAT', 'Seat')], max_length=20),
        ),
    ]
