# Generated by Django 6.0.4 on 2026-06-02 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_floormapobject_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatassignment',
            name='change_type',
            field=models.CharField(choices=[('NEW', 'New assignment'), ('REPLACE', 'Replace current occupant'), ('MOVE', 'Move from another seat'), ('VACATE', 'Vacate seat')], default='NEW', max_length=10),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='from_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_move_outs', to='core.seat'),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_seat_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('VACATED', 'Vacated')], default='ACTIVE', max_length=10),
        ),
    ]
