# Generated by Django 6.0.4 on 2026-06-02 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_seatassignment_change_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultcredential',
            name='visibility',
            field=models.CharField(choices=[('ORG', 'Organization'), ('PRIVATE', 'Private')], default='ORG', max_length=10),
        ),
        migrations.CreateModel(
            name='VaultUserKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_pem', models.TextField()),
                ('encrypted_private_key', models.TextField()),
                ('kdf_salt', models.CharField(max_length=64)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaultShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sealed_secret', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_revealed_at', models.DateTimeField(blank=True, null=True)),
                ('reveal_count', models.PositiveIntegerField(default=0)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.vaultcredential')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_shares_received', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_shares_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('credential', 'recipient')},
            },
        ),
    ]
