# Generated by Django 6.0.4 on 2026-06-04 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_bill_billentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='expense',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.bill'),
        ),
        migrations.DeleteModel(
            name='BillEntry',
        ),
    ]
