# Generated by Django 6.0.4 on 2026-06-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='billpayment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payments', to='core.budgetcategory'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payments', to='core.expense'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='paid_from',
            field=models.CharField(choices=[('COMPANY', 'Company Accounts (direct)'), ('IT', 'IT Budget')], default='IT', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='linked_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.asset'),
        ),
        migrations.AddField(
            model_name='expense',
            name='linked_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.softwarelicense'),
        ),
        migrations.AddField(
            model_name='expense',
            name='linked_purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.purchaserequest'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.vendor'),
        ),
        migrations.AddField(
            model_name='income',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='core.vendor'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('PETTY_CASH', 'Petty Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online / UPI'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payments', to='core.incomesource'),
        ),
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.incomesource'),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='core.incomesource'),
        ),
    ]
