# Generated by Django 6.0.4 on 2026-06-06 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_expense_vendor_remove_income_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='enforce_budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringbill',
            name='auto_pay_from',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('IT', 'IT Budget')], default='COMPANY', max_length=10),
        ),
        migrations.AddField(
            model_name='recurringbill',
            name='auto_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringincome',
            name='auto_post',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExpenseApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='core.expense')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
    ]
