# Generated by Django 6.0.4 on 2026-06-06 12:00

import core.rbac
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_budgetcategory_enforce_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False)),
                ('permissions', models.JSONField(default=core.rbac.blank_permissions)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_system', 'name'],
            },
        ),
    ]
