# Generated by Django 6.0.4 on 2026-07-16 10:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_subscription_permissions(apps, schema_editor):
    """Add the new module without changing any existing permission choice."""
    Role = apps.get_model('core', 'Role')
    grants = {
        'SUPERADMIN': {'view': True, 'add': True, 'edit': True, 'delete': True},
        'ADMIN': {'view': True, 'add': True, 'edit': True, 'delete': True},
        'MANAGER': {'view': True, 'add': True, 'edit': True, 'delete': False},
        'VIEWER': {'view': True, 'add': False, 'edit': False, 'delete': False},
        'ACCOUNTS': {'view': True, 'add': True, 'edit': True, 'delete': False},
    }
    denied = {'view': False, 'add': False, 'edit': False, 'delete': False}
    for role in Role.objects.all():
        permissions = dict(role.permissions or {})
        if 'subscriptions' in permissions:
            continue
        permissions['subscriptions'] = grants.get(role.slug, denied).copy()
        role.permissions = permissions
        role.save(update_fields=['permissions'])


def unseed_subscription_permissions(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    for role in Role.objects.all():
        permissions = dict(role.permissions or {})
        if 'subscriptions' not in permissions:
            continue
        permissions.pop('subscriptions')
        role.permissions = permissions
        role.save(update_fields=['permissions'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_assignment_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('platform', models.CharField(max_length=160)),
                ('plan_type', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(choices=[('CLOUD', 'Cloud'), ('AI', 'AI tools'), ('SAAS', 'SaaS'), ('PRODUCTIVITY', 'Productivity'), ('COMMUNICATION', 'Communication'), ('DESIGN', 'Design'), ('DEVELOPMENT', 'Development'), ('SECURITY', 'Security'), ('FINANCE', 'Finance'), ('HR', 'Human resources'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=24)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a three-letter ISO code (for example, USD).', regex='^[A-Z]{3}$')])),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], db_index=True, max_length=12)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('purpose', models.TextField(blank=True, default='')),
                ('team', models.CharField(blank=True, default='', max_length=160)),
                ('url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=12)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_reminder_enabled', models.BooleanField(default=True)),
                ('renewal_reminder_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('cancellation_deadline', models.DateField(blank=True, db_index=True, null=True)),
                ('cancellation_reminder_enabled', models.BooleanField(default=False)),
                ('cancellation_reminder_days', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('RENEWAL', 'Renewal reminder'), ('EXPIRY', 'Expiry reminder'), ('CANCELLATION', 'Cancellation reminder'), ('MONTHLY_BUDGET', 'Monthly budget threshold'), ('YEARLY_BUDGET', 'Yearly budget threshold')], max_length=24)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('message', models.TextField()),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_alert_logs', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='core.subscription')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('notify_owners', models.BooleanField(default=True)),
                ('default_renewal_reminder_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_cancellation_reminder_days', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_currency', models.CharField(default='USD', max_length=3, validators=[django.core.validators.RegexValidator(message='Budget currency must be a three-letter ISO code.', regex='^[A-Z]{3}$')])),
                ('monthly_budget_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('yearly_budget_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_subscription_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'subscription settings',
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'expiry_date'], name='sub_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['currency', 'category'], name='sub_currency_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionalertlog',
            index=models.Index(fields=['alert_type', 'sent_at'], name='sub_alert_type_idx'),
        ),
        migrations.RunPython(
            seed_subscription_permissions,
            unseed_subscription_permissions,
        ),
    ]
