# Generated by Django 6.0.4 on 2026-07-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_subscriptions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='subscription_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__gte', models.F('start_date'))), name='subscription_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('cancellation_deadline__isnull', True), models.Q(('cancellation_deadline__gte', models.F('start_date')), ('cancellation_deadline__lte', models.F('expiry_date'))), _connector='OR'), name='subscription_cancellation_date_ordered'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionsettings',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_budget_threshold__isnull', True), ('monthly_budget_threshold__gte', 0), _connector='OR'), name='subscription_monthly_budget_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionsettings',
            constraint=models.CheckConstraint(condition=models.Q(('yearly_budget_threshold__isnull', True), ('yearly_budget_threshold__gte', 0), _connector='OR'), name='subscription_yearly_budget_nonnegative'),
        ),
    ]
