# Generated by Django 6.0.4 on 2026-07-16 11:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def disable_zero_budget_thresholds(apps, schema_editor):
    subscription_settings = apps.get_model('core', 'SubscriptionSettings')
    subscription_settings.objects.filter(
        monthly_budget_threshold=0,
    ).update(monthly_budget_threshold=None)
    subscription_settings.objects.filter(
        yearly_budget_threshold=0,
    ).update(yearly_budget_threshold=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_subscription_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptionsettings',
            name='subscription_monthly_budget_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionsettings',
            name='subscription_yearly_budget_nonnegative',
        ),
        migrations.RunPython(
            disable_zero_budget_thresholds,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='subscriptionsettings',
            name='monthly_budget_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='subscriptionsettings',
            name='yearly_budget_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='subscriptionsettings',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_budget_threshold__isnull', True), ('monthly_budget_threshold__gt', 0), _connector='OR'), name='subscription_monthly_budget_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionsettings',
            constraint=models.CheckConstraint(condition=models.Q(('yearly_budget_threshold__isnull', True), ('yearly_budget_threshold__gt', 0), _connector='OR'), name='subscription_yearly_budget_positive'),
        ),
    ]
