# Generated by Django 6.0.4 on 2026-07-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_subscription_budget_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='linked_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='budget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.budgetcategory'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='linked_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_subscriptions', to='core.softwarelicense'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='vault_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.vaultcredential'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.vendor'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='vendor_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.vendorcontract'),
        ),
    ]
