# Generated by Django 6.0.4 on 2026-07-20 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_subscription_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='seats_total',
            field=models.IntegerField(blank=True, help_text='Total licensed seats. Null = unlimited.', null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('revoked_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('subscription', 'user'), name='unique_active_subscription_assignment')],
            },
        ),
    ]
