# Generated by Django 6.0.4 on 2026-07-20 12:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_subscription_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_expiry', models.DateField(blank=True, null=True)),
                ('new_expiry', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('seats_added', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
                ('renewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_renewals_done', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='core.subscription')),
            ],
            options={
                'ordering': ['-renewed_at'],
            },
        ),
    ]
