# Generated by Django 6.0.4 on 2026-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_subscription_renewals'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=160)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Unticked values stay in existing records but disappear from dropdowns.')),
                ('is_system', models.BooleanField(default=False, editable=False, help_text='Application logic depends on this code; it cannot be renamed or removed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'list of values entry',
                'verbose_name_plural': 'lists of values',
                'ordering': ['group', 'sort_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('group', 'code'), name='unique_lov_group_code')],
            },
        ),
    ]
