# Generated by Django 6.0.4 on 2026-07-21 10:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_list_of_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(db_index=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a three-letter ISO code (for example, USD).', regex='^[A-Z]{3}$')])),
                ('currency', models.CharField(db_index=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a three-letter ISO code (for example, USD).', regex='^[A-Z]{3}$')])),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))])),
                ('as_of', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Entered manually'), ('API', 'Fetched from provider')], default='MANUAL', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-as_of', 'currency'],
                'indexes': [models.Index(fields=['base_currency', 'currency', '-as_of'], name='fx_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'currency', 'as_of'), name='unique_rate_per_day'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='exchange_rate_positive')],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('EXCHANGE_RATES', 'Currency exchange rates')], db_index=True, max_length=64, unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Unticked integrations are never contacted.')),
                ('base_url', models.URLField(blank=True, default='')),
                ('encrypted_api_key', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=16)),
                ('last_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
    ]
