# Generated by Django 6.0.4 on 2026-07-21 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_integrations_and_fx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarFeedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('include', models.JSONField(blank=True, default=list)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_feed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
