# Generated by Django 6.0.4 on 2026-07-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_calendar_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('EXCHANGE_RATES', 'Currency exchange rates'), ('SLACK', 'Slack notifications'), ('TEAMS', 'Microsoft Teams notifications'), ('DISCORD', 'Discord notifications'), ('WEBHOOK', 'Outgoing webhook')], db_index=True, max_length=64, unique=True),
        ),
    ]
