# Generated by Django 6.0.4 on 2026-07-22 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_notification_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('MIKROTIK', 'MikroTik RouterOS'), ('PFSENSE', 'pfSense / OPNsense'), ('NTOPNG', 'ntopng'), ('GENERIC', 'Generic REST endpoint')], db_index=True, max_length=32)),
                ('host', models.CharField(help_text="Hostname or IP of the device's management interface.", max_length=255)),
                ('port', models.PositiveIntegerField(default=443)),
                ('use_tls', models.BooleanField(default=True)),
                ('verify_tls', models.BooleanField(default=False, help_text='Most network gear ships a self-signed certificate; leave off unless you have installed a trusted one.')),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('encrypted_secret', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=16)),
                ('last_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_network_integrations', to=settings.AUTH_USER_MODEL)),
                ('pools', models.ManyToManyField(blank=True, related_name='integrations', to='core.ipaddresspool')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SWEEP', 'Network sweep'), ('INTEGRATION', 'Device integration')], default='SWEEP', max_length=16)),
                ('target', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='RUNNING', max_length=12)),
                ('hosts_scanned', models.PositiveIntegerField(default=0)),
                ('hosts_found', models.PositiveIntegerField(default=0)),
                ('hosts_new', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='core.networkintegration')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='core.ipaddresspool')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('mac_address', models.CharField(blank=True, db_index=True, default='', max_length=17)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_guess', models.CharField(blank=True, default='', help_text='Manufacturer inferred from the MAC address prefix.', max_length=120)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('discovered_via', models.CharField(blank=True, default='SWEEP', max_length=64)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('LINKED', 'Linked to a device'), ('IGNORED', 'Ignored')], db_index=True, default='NEW', max_length=12)),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('linked_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_hosts', to='core.networkdevice')),
                ('last_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='core.networkscan')),
            ],
            options={
                'ordering': ['ip_address'],
            },
        ),
        migrations.AddConstraint(
            model_name='networkintegration',
            constraint=models.UniqueConstraint(fields=('kind', 'host'), name='unique_integration_host'),
        ),
        migrations.AddConstraint(
            model_name='discoveredhost',
            constraint=models.UniqueConstraint(fields=('ip_address',), name='unique_discovered_ip'),
        ),
    ]
