# Generated by Django 6.0.4 on 2026-07-22 09:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_network_discovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_descriptor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('BREX', 'Brex'), ('MANUAL', 'Entered manually')], default='BREX', max_length=16)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('last_four', models.CharField(db_index=True, max_length=4)),
                ('nickname', models.CharField(blank=True, default='', max_length=160)),
                ('holder_name', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('TERMINATED', 'Terminated'), ('UNKNOWN', 'Unknown')], default='ACTIVE', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holder', models.ForeignKey(blank=True, help_text='Matched to a person by email where the provider gives one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_four'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_card',
            field=models.ForeignKey(blank=True, help_text='The card this renews on. Set automatically when charges are synced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.paymentcard'),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='BREX', max_length=16)),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('merchant', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('posted_at', models.DateField(db_index=True)),
                ('match_source', models.CharField(choices=[('AUTO', 'Matched automatically'), ('MANUAL', 'Linked by a person'), ('NONE', 'Not matched')], default='NONE', max_length=8)),
                ('match_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.paymentcard')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.subscription')),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentcard',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('provider', 'external_id'), name='unique_provider_card'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['subscription', '-posted_at'], name='payment_sub_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionpayment',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_provider_payment'),
        ),
    ]
