# Generated by Django 6.0.4 on 2026-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_brex_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='wall_height_units',
            field=models.IntegerField(default=3),
        ),
    ]
