# Generated by Django 6.0.4 on 2026-07-23 12:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_floor_wall_height_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CLOUD', 'Cloud'), ('AI', 'AI tools'), ('SAAS', 'SaaS'), ('PRODUCTIVITY', 'Productivity'), ('COMMUNICATION', 'Communication'), ('DESIGN', 'Design'), ('DEVELOPMENT', 'Development'), ('SECURITY', 'Security'), ('FINANCE', 'Finance'), ('HR', 'Human resources'), ('OTHER', 'Other')], db_index=True, max_length=24, unique=True)),
                ('monthly_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('yearly_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
