# Generated by Django 6.0.4 on 2026-07-28 06:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_subscriptioncategorybudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('brand_color', models.CharField(blank=True, default='', help_text="Hex colour used for this provider's chip and chart segment.", max_length=7, validators=[django.core.validators.RegexValidator(message='Brand colour must be a hex value such as #ff9900.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('console_url', models.URLField(blank=True, default='')),
                ('logo_initial', models.CharField(blank=True, default='', help_text='One or two letters shown when there is no logo. Defaults to the first letter of the name.', max_length=2)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive providers stay on existing accounts but disappear from pickers.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, help_text='Link when this provider is also invoiced as a vendor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estate_providers', to='core.vendor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
