# Generated by Django 6.0.4 on 2026-07-28 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_estate_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_email', models.CharField(max_length=255)),
                ('auth_method', models.CharField(choices=[('PASSWORD', 'Password'), ('SSO', 'Single sign-on'), ('API_KEY', 'API key'), ('IAM', 'IAM / identity centre'), ('OTHER', 'Other')], default='PASSWORD', max_length=16)),
                ('mfa_method', models.CharField(choices=[('APP', 'Authenticator app'), ('KEY', 'Hardware key'), ('SMS', 'SMS'), ('NONE', 'None'), ('UNKNOWN', 'Not recorded')], default='UNKNOWN', help_text="'Not recorded' is not the same as 'none' — leave it until someone checks.", max_length=16)),
                ('console_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_workspace', models.ForeignKey(blank=True, help_text='Optional link to the pre-existing vault Account Workspace for the same login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_accounts', to='core.accountworkspace')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_provider_accounts', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='Deleting a provider that still has accounts is blocked.', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.provider')),
                ('vault_credential', models.ForeignKey(blank=True, help_text='The vault entry holding this login. Only its title is ever exposed here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_accounts', to='core.vaultcredential')),
            ],
            options={
                'ordering': ['provider__name', 'login_email'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'login_email'), name='unique_login_per_provider')],
            },
        ),
    ]
