# Generated by Django 6.0.4 on 2026-07-28 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_estate_provider_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The domain or app identifier, e.g. example.com.', max_length=190, unique=True)),
                ('kind', models.CharField(choices=[('MOBILE_GAME', 'Mobile game'), ('APP', 'App'), ('MARKETING', 'Marketing site'), ('CORPORATE', 'Corporate site'), ('STUDIO', 'Studio site'), ('INFRA', 'Infrastructure domain'), ('PARKED', 'Parked'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Retired properties keep their history but drop out of gap reporting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_properties', to='core.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_digital_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'digital properties',
                'ordering': ['name'],
            },
        ),
    ]
