# Generated by Django 6.0.4 on 2026-07-28 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_estate_digital_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='digital_property',
            field=models.ForeignKey(blank=True, help_text='What this service keeps running. Empty means orphaned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.digitalproperty'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='identifier',
            field=models.CharField(blank=True, default='', help_text='What this service actually points at — "zone: example.com", "ecs-prod · ap-south-1".', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='provider_account',
            field=models.ForeignKey(blank=True, help_text='The provider login this service is bought through.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.provideraccount'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='service_layer',
            field=models.CharField(blank=True, choices=[('REGISTRAR', 'Registrar'), ('DNS', 'DNS'), ('HOSTING', 'Hosting'), ('MAIL', 'Mail'), ('CDN', 'CDN'), ('TLS', 'TLS'), ('ANALYTICS', 'Analytics'), ('STORAGE', 'Storage'), ('MONITORING', 'Monitoring'), ('OTHER', 'Other')], help_text='Where this sits in the stack: registrar, DNS, hosting, …', max_length=16, null=True),
        ),
    ]
