# Generated by Django 6.0.4 on 2026-07-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_subscription_estate_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='digitalproperty',
            index=models.Index(fields=['is_active', 'kind'], name='estate_prop_active_idx'),
        ),
        migrations.AddIndex(
            model_name='provideraccount',
            index=models.Index(fields=['provider', 'is_active'], name='estate_acct_prov_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['digital_property', 'service_layer'], name='sub_prop_layer_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['provider_account', 'status'], name='sub_acct_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['auto_renew', 'expiry_date'], name='sub_autorenew_exp_idx'),
        ),
    ]
