# Generated by Django 6.0.4 on 2026-07-28 12:02

import core.models.estate
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_estate_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('EXCHANGE_RATES', 'Currency exchange rates'), ('BREX', 'Brex corporate cards'), ('SLACK', 'Slack notifications'), ('TEAMS', 'Microsoft Teams notifications'), ('DISCORD', 'Discord notifications'), ('WEBHOOK', 'Outgoing webhook'), ('AWS_DISCOVERY', 'AWS (estate discovery)'), ('CLOUDFLARE_DISCOVERY', 'Cloudflare (estate discovery)')], db_index=True, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='EstateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_layers', models.JSONField(default=core.models.estate.default_enabled_layers, help_text='Ordered layer codes this organisation tracks. Empty means every layer.')),
                ('renewal_warning_days', models.PositiveSmallIntegerField(default=30, help_text='A renewal inside this many days is amber, and counts as at-risk when auto-renew is off.', validators=[django.core.validators.MinValueValidator(1)])),
                ('renewal_urgent_days', models.PositiveSmallIntegerField(default=7, help_text='A renewal inside this many days is red.', validators=[django.core.validators.MinValueValidator(1)])),
                ('timeline_window_days', models.PositiveSmallIntegerField(default=90, help_text='How far ahead the renewal timeline looks.', validators=[django.core.validators.MinValueValidator(7)])),
                ('alert_on_auto_renew_off', models.BooleanField(default=True, help_text='Warn when a service approaching renewal will not renew itself.')),
                ('alert_on_new_orphan', models.BooleanField(default=True, help_text='Warn when a service is billed but tied to no property.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_estate_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'estate settings',
            },
        ),
    ]
