# Generated by Django 6.0.4 on 2026-07-28 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_estate_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringbill',
            name='linked_subscription',
            field=models.ForeignKey(blank=True, help_text='The subscription this bill was raised from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bills', to='core.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionsettings',
            name='create_expense_on_renewal',
            field=models.BooleanField(default=False, help_text="When a renewal is recorded, raise a pending expense against the subscription's budget category. Requires a category and an active financial year; nothing is booked without both."),
        ),
    ]
