# Generated by Django 6.0.4 on 2026-07-29 06:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_estate_rename_property_and_account_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='service_layer',
            field=models.CharField(blank=True, choices=[('REGISTRAR', 'Registrar'), ('DNS', 'DNS'), ('HOSTING', 'Hosting'), ('MAIL', 'Mail'), ('CDN', 'CDN'), ('TLS', 'TLS'), ('ANALYTICS', 'Analytics'), ('SAAS', 'SaaS'), ('STORAGE', 'Storage'), ('MONITORING', 'Monitoring'), ('OTHER', 'Other')], help_text='Where this sits in the stack: registrar, DNS, hosting, …', max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('REGISTRAR', 'Registrar'), ('DNS', 'DNS'), ('HOSTING', 'Hosting'), ('MAIL', 'Mail'), ('CDN', 'CDN'), ('TLS', 'TLS'), ('ANALYTICS', 'Analytics'), ('SAAS', 'SaaS'), ('STORAGE', 'Storage'), ('MONITORING', 'Monitoring'), ('OTHER', 'Other')], db_index=True, help_text='Both the category and, for the seven stack roles, the stack position.', max_length=16)),
                ('identifier', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('AT_RISK', 'At risk'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=16)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True, help_text='Off plus a near renewal date is what makes a service at-risk.')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('USAGE', 'Usage-based'), ('FREE', 'Free')], default='MONTHLY', max_length=16)),
                ('console_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, help_text='What this service keeps running. Null means orphaned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.property')),
                ('provider', models.ForeignKey(help_text='Deleting a provider that still has services is blocked.', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.provider')),
                ('provider_account', models.ForeignKey(help_text='The login this service is bought through.', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.provideraccount')),
                ('vault_credential', models.ForeignKey(blank=True, help_text='The vault entry for this service. Only its id and title are ever exposed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estate_services', to='core.vaultcredential')),
            ],
            options={
                'ordering': ['property__name', 'service_type', 'identifier'],
                'indexes': [models.Index(fields=['property', 'service_type'], name='estate_svc_prop_type_idx'), models.Index(fields=['provider_account', 'status'], name='estate_svc_acct_stat_idx'), models.Index(fields=['auto_renew', 'renewal_date'], name='estate_svc_auto_renew_idx'), models.Index(fields=['status', 'renewal_date'], name='estate_svc_stat_renew_idx')],
            },
        ),
    ]
