# Generated by Django 6.0.4 on 2026-08-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_retire_licenses_and_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='key_expires_at',
            field=models.DateField(blank=True, help_text='Optional. When this token expires, so it can be rotated before it fails.', null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='key_fingerprint',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='integration',
            name='key_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
