# Generated by Django 6.0.4 on 2026-08-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_integration_credential_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='integration',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='external_owner_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='form',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('VIRTUAL', 'Virtual'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='limit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='limit_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='limit_interval',
            field=models.CharField(blank=True, default='', help_text='How often the limit resets, as the provider words it.', max_length=32),
        ),
        migrations.CreateModel(
            name='BrexObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('CARD', 'Card'), ('USER', 'User'), ('CARD_ACCOUNT', 'Card account'), ('DEPARTMENT', 'Department'), ('TRANSACTION', 'Card transaction')], db_index=True, max_length=32)),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('last_changed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['object_type', 'external_id'],
                'indexes': [models.Index(fields=['object_type', '-last_seen_at'], name='brex_obj_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('object_type', 'external_id'), name='unique_brex_object')],
            },
        ),
        migrations.CreateModel(
            name='CardAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='BREX', max_length=16)),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'external_id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_provider_card_account')],
            },
        ),
    ]
