# Generated by Django 6.0.4 on 2026-08-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_brex_object_and_card_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepayment',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='servicepayment',
            name='base_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='servicepayment',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='servicepayment',
            name='fx_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='servicepayment',
            index=models.Index(fields=['base_amount', 'posted_at'], name='payment_unconverted_idx'),
        ),
    ]
