# Generated by Django 6.0.4 on 2026-08-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_payment_fx_at_charge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepayment',
            name='match_source',
            field=models.CharField(choices=[('AUTO', 'Matched automatically'), ('MANUAL', 'Set by a person'), ('NONE', 'Not matched')], default='NONE', max_length=8),
        ),
    ]
