# Generated by Django 6.0.4 on 2026-08-13 10:52

import core.estate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_merge_brex_and_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='kind',
            field=models.CharField(choices=core.estate.property_kind_choices, db_index=True, default='OTHER', max_length=24),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=core.estate.service_type_choices, db_index=True, help_text='Both the category and, for the seven stack roles, the stack position.', max_length=16),
        ),
    ]
