# Generated by Django 6.0.4 on 2026-08-18 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_estate_extensible_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideraccount',
            name='login_kind',
            field=models.CharField(choices=[('EMAIL', 'Email address'), ('USERNAME', 'Username'), ('ACCOUNT_ID', 'Account ID / number'), ('PHONE', 'Phone number')], default='EMAIL', help_text='What this login string is. Plenty of providers issue a username rather than an email.', max_length=12),
        ),
        migrations.AlterField(
            model_name='provideraccount',
            name='account_email',
            field=models.CharField(max_length=255, verbose_name='login'),
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('login_kind', models.CharField(choices=[('EMAIL', 'Email address'), ('USERNAME', 'Username'), ('ACCOUNT_ID', 'Account ID / number'), ('PHONE', 'Phone number')], default='EMAIL', max_length=12)),
                ('display_name', models.CharField(blank=True, default='', max_length=160)),
                ('role', models.CharField(choices=[('OWNER', 'Owner / root'), ('ADMIN', 'Administrator'), ('BILLING', 'Billing only'), ('MEMBER', 'Member'), ('READONLY', 'Read only')], default='MEMBER', max_length=12)),
                ('mfa_type', models.CharField(choices=[('SECURITY_KEY', 'Security key'), ('APP', 'Authenticator app'), ('SMS', 'SMS'), ('NONE', 'None'), ('UNKNOWN', 'Not recorded')], default='UNKNOWN', help_text="'Not recorded' is not the same as 'none' — leave it until someone checks.", max_length=16)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Clear this when the login is removed at the provider, rather than deleting the row.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_account', models.ForeignKey(help_text='The account this login gets into. Deleting the account removes its logins.', on_delete=django.db.models.deletion.CASCADE, related_name='people', to='core.provideraccount')),
                ('user', models.ForeignKey(blank=True, help_text='Link to the person in IT Command, when this login belongs to one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'account login',
                'verbose_name_plural': 'account logins',
                'ordering': ['provider_account__provider__name', 'login'],
                'indexes': [models.Index(fields=['user'], name='estate_acctuser_user_idx'), models.Index(fields=['mfa_type'], name='estate_acctuser_mfa_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_account', 'login'), name='unique_login_per_account')],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hostname or console name, e.g. web-01.', max_length=160)),
                ('server_role', models.CharField(choices=[('WEB', 'Web server'), ('APP', 'Application server'), ('DATABASE', 'Database'), ('CACHE', 'Cache'), ('WORKER', 'Worker / queue'), ('BUILD', 'Build / CI'), ('STORAGE', 'Storage'), ('VPN', 'VPN / gateway'), ('GAME', 'Game server'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('environment', models.CharField(choices=[('PRODUCTION', 'Production'), ('STAGING', 'Staging'), ('DEVELOPMENT', 'Development'), ('TEST', 'Test'), ('DR', 'Disaster recovery')], default='PRODUCTION', max_length=12)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('SUSPENDED', 'Suspended'), ('MAINTENANCE', 'Maintenance'), ('DECOMMISSIONED', 'Decommissioned')], default='RUNNING', max_length=16)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('private_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, default='', help_text='Full DNS name, if it has one.', max_length=253)),
                ('region', models.CharField(blank=True, default='', help_text='e.g. eu-west-1.', max_length=60)),
                ('size', models.CharField(blank=True, default='', help_text='Instance type or plan, e.g. t3.medium.', max_length=60)),
                ('operating_system', models.CharField(blank=True, default='', max_length=80)),
                ('provisioned_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, help_text='For a fixed-term or prepaid box.', null=True)),
                ('console_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_servers', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, help_text='What it keeps running. Blank means nothing claims it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='core.property')),
                ('provider_account', models.ForeignKey(help_text='Which login pays for it. Deleting an account with servers is blocked.', on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='core.provideraccount')),
                ('service', models.ForeignKey(blank=True, help_text='The service this is billed under, if one covers it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='core.service')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='estate_server_status_idx'), models.Index(fields=['environment'], name='estate_server_env_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_account', 'name'), name='unique_server_name_per_account')],
            },
        ),
    ]
