# Generated by Django 6.0.4 on 2026-08-18 09:56

import core.estate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_provideraccount_login_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='hosting',
            field=models.CharField(choices=core.estate.server_hosting_choices, default='CLOUD', help_text='Cloud, on-site, colocation. Extendable from Settings.', max_length=16),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_role',
            field=models.CharField(choices=core.estate.server_role_choices, default='OTHER', max_length=16),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['hosting'], name='estate_server_hosting_idx'),
        ),
    ]
