# Generated by Django 6.0.4 on 2026-08-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_server_hosting_alter_server_server_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_source',
            field=models.CharField(choices=[('LOCAL', 'Local password'), ('MAILBOX', 'Mailbox (Dovecot)')], default='LOCAL', help_text="Which system decides whether this account's password is correct.", max_length=10),
        ),
    ]
