# Generated by Django 6.0.4 on 2026-08-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_user_auth_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('EXCHANGE_RATES', 'Currency exchange rates'), ('BREX', 'Brex corporate cards'), ('SLACK', 'Slack notifications'), ('TEAMS', 'Microsoft Teams notifications'), ('DISCORD', 'Discord notifications'), ('WEBHOOK', 'Outgoing webhook'), ('AWS_DISCOVERY', 'AWS (estate discovery)'), ('CLOUDFLARE_DISCOVERY', 'Cloudflare (estate discovery)'), ('CPANEL', 'cPanel mailboxes')], db_index=True, max_length=64, unique=True),
        ),
    ]
