# Generated by Django 6.0.4 on 2026-08-21 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_integration_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(db_index=True, max_length=320, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('quota_mb', models.IntegerField(blank=True, null=True)),
                ('disk_used_mb', models.IntegerField(default=0)),
                ('suspended', models.BooleanField(default=False)),
                ('exists_in_cpanel', models.BooleanField(default=True)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_requested_by', models.CharField(blank=True, default='', max_length=320)),
                ('deletion_reason', models.TextField(blank=True, default='')),
                ('purge_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'managed mailbox',
                'verbose_name_plural': 'managed mailboxes',
                'ordering': ['address'],
            },
        ),
    ]
