# Generated by Django 6.0.4 on 2026-08-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_managed_mailbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedmailbox',
            name='mail_app_enabled',
            field=models.BooleanField(default=True, help_text='Allow this mailbox to be opened in Terafort Mail.'),
        ),
    ]
