"""
Django settings for itcommand_backend project.

Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'core.User'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)


def _csv(value):
    """Parse a comma-separated env value into a clean list of strings."""
    return [item.strip() for item in str(value).split(',') if item.strip()]


# Hosts/domains this site can serve. In production set ALLOWED_HOSTS in the
# environment to your server's domain and/or IP (comma-separated).
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
    cast=_csv,
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'simple_history',
    # Local
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves collected static files (e.g. the Django admin) directly
    # from the app, so it works even without a separate static file server.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Last: it reads request.user, so it has to sit after authentication, and
    # it only records what already happened.
    'core.presence.LastSeenMiddleware',
]

ROOT_URLCONF = 'itcommand_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'itcommand_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DB_NAME = config('DB_NAME', default='')

if DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = config('TIME_ZONE', default='UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# `collectstatic` gathers everything here; nginx (and/or WhiteNoise) serves it.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads — avatars, bills, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# FileField/ImageField URLs are signed API links instead of predictable public
# /media paths. In Docker, Django authorizes the signature and delegates the
# actual bytes to nginx through an internal X-Accel-Redirect location.
STORAGES = {
    'default': {
        'BACKEND': 'core.storage.ProtectedMediaStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}
PROTECTED_MEDIA_URL_TTL = max(
    60, config('PROTECTED_MEDIA_URL_TTL', default=3600, cast=int)
)
PROTECTED_MEDIA_USE_X_ACCEL = config(
    'PROTECTED_MEDIA_USE_X_ACCEL', default=not DEBUG, cast=bool
)

# Behind a TLS-terminating reverse proxy (e.g. nginx), trust the forwarded
# protocol header so Django knows the original request was HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Production transport/cookie hardening. These remain disabled by default so
# plain-HTTP local development continues to work. Enable them only after HTTPS
# termination and trusted forwarding are configured.
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    'SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool
)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
        'vault_unlock': '5/min',
        'vault_reveal': '30/min',
    },
}

# Simple JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS — origins (scheme://host[:port]) allowed to call the API from a browser.
# When the frontend is served from the same origin as the API (the default
# Docker/nginx setup), CORS is effectively a no-op, but it's kept env-driven so
# the frontend can also run on a separate origin during development.
# The mailbox session id rides in an httpOnly cookie, so the browser has to be
# allowed to store and send it across the frontend/API origin split. Safe only
# with an explicit origin list below — the spec forbids pairing credentials
# with a wildcard, and the browser will refuse it.
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:3001',
    cast=_csv,
)

# Trusted origins for CSRF (needed for the Django admin when DEBUG=False and
# served over a domain). Set CSRF_TRUSTED_ORIGINS in the environment, e.g.
# "https://itcommand.example.com".
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=_csv)

from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-vault-token',
]


# Email. Local development prints messages to the console; production uses
# SMTP unless EMAIL_BACKEND explicitly selects another Django backend.
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default=(
        'django.core.mail.backends.console.EmailBackend'
        if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
    ),
)
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='itcommand@localhost')


# Long-lived automation runner settings (used by the Docker automation service).
AUTOMATION_DAILY_COMMANDS = config(
    'AUTOMATION_DAILY_COMMANDS',
    # The subscription and licence commands were removed in Phase 5 with the
    # modules they served. An existing deployment's .env may still name them;
    # `run_automation` skips a command that no longer exists rather than
    # failing the whole cycle on it.
    # backfill_payment_fx runs after fetch_exchange_rates so it sees the rates
    # that arrived this morning, and after sync_brex so it sees today's charges.
    default=(
        'finance_autopost,fetch_exchange_rates,sync_brex,'
        'backfill_payment_fx,check_contract_alerts'
    ),
    cast=_csv,
)
AUTOMATION_INTERVAL_COMMANDS = config(
    'AUTOMATION_INTERVAL_COMMANDS',
    # Was `check_subscription_alerts`, removed in Phase 5. Nothing runs on the
    # short cadence now; the estate has no alerting pipeline of its own yet.
    default='',
    cast=_csv,
)
AUTOMATION_INTERVAL_SECONDS = max(
    30, config('AUTOMATION_INTERVAL_SECONDS', default=300, cast=int)
)
AUTOMATION_POLL_SECONDS = max(
    10, config('AUTOMATION_POLL_SECONDS', default=60, cast=int)
)
AUTOMATION_RETRY_SECONDS = max(
    30, config('AUTOMATION_RETRY_SECONDS', default=300, cast=int)
)
AUTOMATION_PING_ENABLED = config(
    'AUTOMATION_PING_ENABLED', default=True, cast=bool
)
PING_CHECK_INTERVAL_SECONDS = max(
    30, config('PING_CHECK_INTERVAL_SECONDS', default=300, cast=int)
)
AUTOMATION_EMAIL_REPORT_ENABLED = config(
    'AUTOMATION_EMAIL_REPORT_ENABLED', default=False, cast=bool
)
FINANCE_REPORT_DAY = min(
    28, max(1, config('FINANCE_REPORT_DAY', default=1, cast=int))
)


# ---------------------------------------------------------------------------
# Terafort Mail bridge
#
# Everything here is inert while MAIL_AUTH_ENABLED is False, which is the
# default. With the flag off, LoginView takes exactly the path it always has
# and the two new routes return 404. Rolling back the mailbox-auth feature is
# setting this one variable to false -- no migration, no data change; existing
# password hashes are left on the row, dormant, until you sign off on removing
# them separately.
# ---------------------------------------------------------------------------
MAIL_AUTH_ENABLED = config('MAIL_AUTH_ENABLED', default=False, cast=bool)

# Where the mail app lives. The internal URL is reached over the compose
# network and is never exposed publicly.
MAIL_APP_INTERNAL_URL = config('MAIL_APP_INTERNAL_URL', default='http://mail-backend:8000')
MAIL_APP_HANDOFF_URL = config('MAIL_APP_HANDOFF_URL', default='https://mail.itcommand.com/auth/handoff')
MAIL_APP_TIMEOUT = config('MAIL_APP_TIMEOUT', default=20, cast=int)

# Dovecot. Only used when MAIL_AUTH_ENABLED is on.
MAIL_IMAP_HOST = config('MAIL_IMAP_HOST', default='')
MAIL_IMAP_PORT = config('MAIL_IMAP_PORT', default=993, cast=int)
MAIL_IMAP_VERIFY_CERT = config('MAIL_IMAP_VERIFY_CERT', default=True, cast=bool)
MAIL_IMAP_TIMEOUT = config('MAIL_IMAP_TIMEOUT', default=15, cast=int)

# Shared with the mail app. All three must match on both sides.
MAIL_SESSION_SEAL_KEY = config('MAIL_SESSION_SEAL_KEY', default='0' * 32)
MAIL_HANDOFF_HMAC_KEY = config('MAIL_HANDOFF_HMAC_KEY', default='dev-handoff-key')
MAIL_INTERNAL_HMAC_KEY = config('MAIL_INTERNAL_HMAC_KEY', default='')
MAIL_INTERNAL_SERVICE_NAME = config('MAIL_INTERNAL_SERVICE_NAME', default='itcommand')

MAIL_REDIS_URL = config('MAIL_REDIS_URL', default='')
MAIL_SESSION_ABSOLUTE_SECONDS = config('MAIL_SESSION_ABSOLUTE_SECONDS', default=8 * 3600, cast=int)
MAIL_HANDOFF_TICKET_SECONDS = config('MAIL_HANDOFF_TICKET_SECONDS', default=30, cast=int)

# httpOnly, host-scoped. The browser never reads this and it never reaches
# localStorage; it exists only so OpenMailboxView can find the mail session.
MAIL_SID_COOKIE = config('MAIL_SID_COOKIE', default='itc_mail_sid')

# Remembers that this browser has already proved a second factor, so a code is
# asked for about once a month rather than at every sign-in. Signed, httpOnly,
# and useless without the mailbox password.
MAIL_DEVICE_COOKIE = config('MAIL_DEVICE_COOKIE', default='itc_2fa_device')

# ---------------------------------------------------------------------------
# TeraMailer — the webmail in /mail
#
# TERAMAILER_URL is where IT Command's server reaches it (internal); the public
# URL is where the *browser* posts the sign-in ticket, and the two differ
# behind a proxy. The shared secret must equal ITC_SHARED_SECRET in the mail
# backend's .env, or every call fails closed.
# ---------------------------------------------------------------------------
TERAMAILER_URL = config('TERAMAILER_URL', default='http://127.0.0.1:5000')
TERAMAILER_PUBLIC_URL = config('TERAMAILER_PUBLIC_URL', default='http://localhost:5000')
TERAMAILER_SHARED_SECRET = config('TERAMAILER_SHARED_SECRET', default='')
TERAMAILER_SERVICE_NAME = config('TERAMAILER_SERVICE_NAME', default='itcommand')
TERAMAILER_WEBMAIL_URL = config('TERAMAILER_WEBMAIL_URL', default='http://localhost:3000')
