"""
Django settings for itcommand_backend project.

Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'core.User'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)


def _csv(value):
    """Parse a comma-separated env value into a clean list of strings."""
    return [item.strip() for item in str(value).split(',') if item.strip()]


# Hosts/domains this site can serve. In production set ALLOWED_HOSTS in the
# environment to your server's domain and/or IP (comma-separated).
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
    cast=_csv,
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'simple_history',
    # Local
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves collected static files (e.g. the Django admin) directly
    # from the app, so it works even without a separate static file server.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'itcommand_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'itcommand_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DB_NAME = config('DB_NAME', default='')

if DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = config('TIME_ZONE', default='UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# `collectstatic` gathers everything here; nginx (and/or WhiteNoise) serves it.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads — avatars, bills, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# FileField/ImageField URLs are signed API links instead of predictable public
# /media paths. In Docker, Django authorizes the signature and delegates the
# actual bytes to nginx through an internal X-Accel-Redirect location.
STORAGES = {
    'default': {
        'BACKEND': 'core.storage.ProtectedMediaStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}
PROTECTED_MEDIA_URL_TTL = max(
    60, config('PROTECTED_MEDIA_URL_TTL', default=3600, cast=int)
)
PROTECTED_MEDIA_USE_X_ACCEL = config(
    'PROTECTED_MEDIA_USE_X_ACCEL', default=not DEBUG, cast=bool
)

# Behind a TLS-terminating reverse proxy (e.g. nginx), trust the forwarded
# protocol header so Django knows the original request was HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Production transport/cookie hardening. These remain disabled by default so
# plain-HTTP local development continues to work. Enable them only after HTTPS
# termination and trusted forwarding are configured.
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    'SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool
)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
        'vault_unlock': '5/min',
        'vault_reveal': '30/min',
    },
}

# Simple JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS — origins (scheme://host[:port]) allowed to call the API from a browser.
# When the frontend is served from the same origin as the API (the default
# Docker/nginx setup), CORS is effectively a no-op, but it's kept env-driven so
# the frontend can also run on a separate origin during development.
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:3001',
    cast=_csv,
)

# Trusted origins for CSRF (needed for the Django admin when DEBUG=False and
# served over a domain). Set CSRF_TRUSTED_ORIGINS in the environment, e.g.
# "https://itcommand.example.com".
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=_csv)

from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-vault-token',
]


# Email. Local development prints messages to the console; production uses
# SMTP unless EMAIL_BACKEND explicitly selects another Django backend.
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default=(
        'django.core.mail.backends.console.EmailBackend'
        if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
    ),
)
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='itcommand@localhost')


# Long-lived automation runner settings (used by the Docker automation service).
AUTOMATION_DAILY_COMMANDS = config(
    'AUTOMATION_DAILY_COMMANDS',
    default=(
        'finance_autopost,auto_renew_licenses,auto_renew_subscriptions,'
        'fetch_exchange_rates,sync_brex,'
        'check_license_alerts,check_contract_alerts'
    ),
    cast=_csv,
)
AUTOMATION_INTERVAL_COMMANDS = config(
    'AUTOMATION_INTERVAL_COMMANDS',
    default='check_subscription_alerts',
    cast=_csv,
)
AUTOMATION_INTERVAL_SECONDS = max(
    30, config('AUTOMATION_INTERVAL_SECONDS', default=300, cast=int)
)
AUTOMATION_POLL_SECONDS = max(
    10, config('AUTOMATION_POLL_SECONDS', default=60, cast=int)
)
AUTOMATION_RETRY_SECONDS = max(
    30, config('AUTOMATION_RETRY_SECONDS', default=300, cast=int)
)
AUTOMATION_PING_ENABLED = config(
    'AUTOMATION_PING_ENABLED', default=True, cast=bool
)
PING_CHECK_INTERVAL_SECONDS = max(
    30, config('PING_CHECK_INTERVAL_SECONDS', default=300, cast=int)
)
AUTOMATION_EMAIL_REPORT_ENABLED = config(
    'AUTOMATION_EMAIL_REPORT_ENABLED', default=False, cast=bool
)
FINANCE_REPORT_DAY = min(
    28, max(1, config('FINANCE_REPORT_DAY', default=1, cast=int))
)
