# Generated by Django 6.0.4 on 2026-08-19 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mailbox_address', models.CharField(db_index=True, max_length=320)),
                ('actor', models.CharField(blank=True, default='', max_length=320)),
                ('action', models.CharField(db_index=True, max_length=48)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'db_table': 'mail_audit_log',
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=320, unique=True)),
                ('itc_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('kek_salt', models.BinaryField()),
                ('wrapped_dek', models.BinaryField()),
                ('dek_generation', models.IntegerField(default=1)),
                ('totp_secret', models.CharField(blank=True, default='', max_length=64)),
                ('totp_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_code_hashes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'mailboxes',
                'db_table': 'mail_mailbox',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imap_path', models.CharField(max_length=512)),
                ('special_use', models.CharField(blank=True, default='', max_length=32)),
                ('uidvalidity', models.BigIntegerField(default=0)),
                ('highest_modseq', models.BigIntegerField(blank=True, null=True)),
                ('unread_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='mailcore.mailbox')),
            ],
            options={
                'db_table': 'mail_folder',
                'unique_together': {('mailbox', 'imap_path')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.BigIntegerField()),
                ('thread_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('message_id_hmac', models.BinaryField(blank=True, null=True)),
                ('internal_date', models.DateTimeField(db_index=True)),
                ('size_bytes', models.IntegerField(default=0)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('bundle', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('envelope_enc', models.BinaryField()),
                ('body_text_enc', models.BinaryField(blank=True, null=True)),
                ('body_html_enc', models.BinaryField(blank=True, null=True)),
                ('has_remote_images', models.BooleanField(default=False)),
                ('images_allowed', models.BooleanField(default=False)),
                ('link_mismatch', models.BooleanField(default=False)),
                ('quarantined', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailcore.folder')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailcore.mailbox')),
            ],
            options={
                'db_table': 'mail_message',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_id', models.CharField(max_length=32)),
                ('filename_enc', models.BinaryField()),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.IntegerField(default=0)),
                ('scan_status', models.CharField(choices=[('pending', 'pending'), ('clean', 'clean'), ('infected', 'infected'), ('failed', 'failed')], default='pending', max_length=16)),
                ('scan_at', models.DateTimeField(blank=True, null=True)),
                ('blob_key', models.CharField(blank=True, default='', max_length=256)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mailcore.mailbox')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mailcore.message')),
            ],
            options={
                'db_table': 'mail_attachment',
            },
        ),
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('SNOOZE_WAKE', 'snooze wake'), ('SEND_LATER', 'send later'), ('UNDO_WINDOW', 'undo window')], max_length=16)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('payload_enc', models.BinaryField()),
                ('state', models.CharField(choices=[('scheduled', 'scheduled'), ('executing', 'executing'), ('done', 'done'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='scheduled', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='mailcore.mailbox')),
            ],
            options={
                'db_table': 'mail_pending_action',
            },
        ),
        migrations.CreateModel(
            name='SearchToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token_hmac', models.BinaryField()),
                ('field', models.SmallIntegerField(default=3)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_tokens', to='mailcore.mailbox')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='mailcore.message')),
            ],
            options={
                'db_table': 'mail_search_token',
            },
        ),
        migrations.CreateModel(
            name='SharedMailboxGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_address', models.CharField(max_length=320)),
                ('granted_by', models.CharField(max_length=320)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('grantee_mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='mailcore.mailbox')),
            ],
            options={
                'db_table': 'mail_shared_grant',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('body_enc', models.BinaryField()),
                ('is_default', models.BooleanField(default=False)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='mailcore.mailbox')),
            ],
            options={
                'db_table': 'mail_signature',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('body_enc', models.BinaryField()),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='mailcore.mailbox')),
            ],
            options={
                'db_table': 'mail_template',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailbox', '-internal_date'], name='mail_messag_mailbox_69e78d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailbox', 'bundle'], name='mail_messag_mailbox_9843c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('folder', 'uid')},
        ),
        migrations.AddIndex(
            model_name='pendingaction',
            index=models.Index(fields=['mailbox', 'state', 'due_at'], name='mail_pendin_mailbox_291c96_idx'),
        ),
        migrations.AddIndex(
            model_name='searchtoken',
            index=models.Index(fields=['mailbox', 'token_hmac'], name='mail_search_mailbox_9aa607_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sharedmailboxgrant',
            unique_together={('shared_address', 'grantee_mailbox')},
        ),
    ]
